// react-client/src/App.tsx
import React, { useState } from "react";
import { io } from "socket.io-client";

function App() {
  const [services, setServices] = useState<any[]>([]);
  const [formData, setFormData] = useState({
    id: "",
    patient: "",
    category: "",
    createdAt: "",
  });

  const socket = io("http://localhost:5000/HAC");

  socket.on("connect", () => {
    console.log("Conectado ao servidor!");
  });

  socket.on("novo serviço", (data) => {
    setServices([...services, data]);
  });

  function acceptService(id: any) {
    setServices(services.filter((service) => service.id !== id));
    socket.emit("aceitar serviço", id);
  }

  const handleInputChange = (e: any) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
      id: (Math.floor(Math.random() * 100) + 1).toString(),
      createdAt: new Date().toISOString(),
    });
  };

  const handleSubmit = (e: any) => {
    e.preventDefault();
    socket.emit("receber serviço", formData);
    setFormData({
      id: "",
      patient: "",
      category: "",
      createdAt: "",
    });
  };

  return (
    <div className="App">
      <div className="App-header">
        <h1>Criar serviço</h1>
        <form onSubmit={handleSubmit} className="form">
          <div className="input-group">
            <label htmlFor="patient">Nome do paciente:</label>
            <input
              type="text"
              id="patient"
              name="patient"
              value={formData.patient}
              onChange={handleInputChange}
            />
          </div>
          <div className="input-group">
            <label htmlFor="category">Categoria:</label>
            <input
              type="text"
              id="category"
              name="category"
              value={formData.category}
              onChange={handleInputChange}
            />
          </div>
          <button type="submit">Criar novo serviço</button>
        </form>
      </div>
      <div className="dashboard">
        <h2>Dashboard</h2>
        <div className="department">
          <h3>Departamento Nutrição</h3>
          <div className="service-list">
            {services.map((service) => (
              <div className="service-card" key={service.id}>
                <p>Número do serviço: {service.id}</p>
                <p>Número do paciente: {service.patient}</p>
                <p>Categoria: {service.category}</p>
                <p>Criado em: {service.createdAt}</p>
                <button onClick={() => acceptService(service.id)}>
                  Aceitar
                </button>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;

// vue-client/src/App.vue
<template>
  <div id="app">
    <h2>WebSocket Client</h2>
    <ul id="services">
      <li
        v-for="service in services"
        :key="service.id"
        :id="service.patient"
        :class="{ 'accepted-service': service.accepted }"
      >
        Paciente: {{ service.patient }}, Categoria: {{ service.category }},
        Criado em: {{ service.createdAt }}
      </li>
    </ul>
    <input type="text" v-model="patient" placeholder="Nome do paciente" />
    <input type="text" v-model="category" placeholder="Categoria do serviço" />
    <button @click="sendMessage">Enviar Serviço</button>
  </div>
</template>

<script>
export default {
  data() {
    return {
      socket: null,
      services: [],
      patient: "",
      category: "",
    };
  },
  mounted() {
    this.socket = io("http://localhost:5000/HAC");

    this.socket.on("connect", () => {
      console.log("Conectado ao servidor!");
    });

    this.socket.on("lista de serviços", (dataList) => {
      this.services = dataList;
    });

    this.socket.on("novo serviço", (data) => {
      this.services.push({ ...data, accepted: false });
    });

    this.socket.on("serviço aceito", (data) => {
      const service = this.services.find((s) => s.patient === data.patient);
      if (service) {
        service.accepted = true;
      }
    });
  },
  methods: {
    sendMessage() {
      const data = {
        id: Math.floor(Math.random() * 100) + 1,
        patient: this.patient,
        category: this.category,
        createdAt: new Date().toISOString(),
      };
      this.socket.emit("receber serviço", data);
      this.patient = "";
      this.category = "";
    },
  },
};
</script>

<style scoped>
/* === CORE STYLES === */
body {
  font-family: Arial, sans-serif;
  background-color: #ffebd9;
  margin: 0;
  padding: 0;
}

/* === LAYOUT STYLES === */
.App {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 20px;
}

.App-header,
.dashboard {
  width: 100%;
  max-width: 500px;
  border-radius: 10px;
  margin-bottom: 20px;
  padding: 20px;
}

.service-list {
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
}

/* === COMPONENT STYLES === */
/* Form */
.form {
  display: flex;
  flex-direction: column;
}

.input-group {
  margin-bottom: 15px;
}

/* Service Card */
.service-card {
  background-color: white;
  padding: 15px;
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  width: 100%;
  max-width: 250px;
}

/* === ELEMENT STYLES === */
input[type="text"] {
  padding: 10px;
  border: 1px solid #ff6b00;
  border-radius: 5px;
  width: 100%;
}

button {
  background-color: #ff6b00;
  color: white;
  border: none;
  padding: 10px 15px;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s;
}

button:hover {
  background-color: #e55a00;
}

/* === UTILITY STYLES === */
.department {
  background-color: #ffe4e1;
  padding: 20px;
  border-radius: 10px;
}

.accepted-service {
  color: #ff6b00; /* Laranja */
  text-decoration: underline; /* Sublinhado */
  text-decoration-color: #ff6b00; /* Cor do sublinhado laranja */
}
</style>
